### ISSUE TITLE
Darbų ir problemų sąrašiuką perkelti į Github'ą

### ISSUE THREAD

**Issue by ViliusKraujutis** [vilnius/meta#1]
Būtų puiku, jeigu tą [darbų sąrašiuką](https://docs.google.com/spreadsheets/d/1-e__ODHSWTnAz5QZ3iGn0EBYZfsGQNCGU1H0Zxu5KJQ/edit#gid=0) persikeltumėte čia į github.com/vilnius repozitorijų issues'us. Galėtume padiskutuoti, ar net padėti su Pull Request'ais.

Ką manai, @povilasp?

**Comment by povilasp** [comment]
Įdėsiu nuorodą į sąrašą į readme, kai ką gal ir persikelsim, bet ne viskas yra Github issuesai, ne viskas net apskritai yra githubas :)
