### ISSUE TITLE
Per daug commit'ų yra iš atvirasvilnius naudotojo

### ISSUE THREAD

**Issue by ViliusKraujutis** [vilnius/meta#2]
Būtų puiku, kad tik bot'as komitintų su @atvirasvilnius vartotojo vardu, o visi kiti būtų konkretaus žmogaus. Pvz [šis](https://github.com/vilnius/biudzetas/commit/caa96d52c036af6bae78913c4c9c01ecab85a975) komitas spėju buvo Povilo Poderskio (@povilasp). Bet ar tikrai? Kas bus, kai daugiau žmonių darys atnaujinimus skriptams?

Bet gal jau prie to pereinat po truputį?

**Comment by povilasp** [comment]
Teisinga mintis, pereinu. Tiesiog kai vienas dirbi tai pritingi.
